version: '3'
services:
  rdb:
    image: mysql:8.0.33
    container_name: member_mysql
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: member_db

  redis:
    image: redis:alpine
    container_name: order_redis
    command: redis-server --requirepass mypassword --port 6379
    hostname: redis
    ports:
      - 16379:6379

#  mongo:
#    image: mongo
#    container_name: dev-mongo
#    ports:
#      - 27017:27017 # HOST:CONTAINER
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 1234
#      MONGO_INITDB_DATABASE: preorder
#  mongo-express:
#    depends_on:
#      - mongodb
#    image: mongo-express
#    container_name: mongo-express
#    ports:
#      - 27117:9090
#    environment:
#      - PORT=9090
#      - ME_CONFIG_MONGODB_PORT=27017
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
#      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/
#    networks:
#      -network-mongo:
#    hostname: mongo-express
#
#networks:
#  network-mongo:
#    driver: bridge

